### ISSUE TITLE
Error propagation to iris-client-fe in case data requests failed

### ISSUE THREAD

**Issue by tboegner** [iris-connect/iris-client#128]
- Generate meaningful error message in Backend
- Show error message to the user in Frontend

**Comment by hey-johnnypark** [comment]
Hi @tboegner , this is a good one. We actually have a similar behaviour when the location search fails with a backend error. Do you think we could add the error handling there as well or should we open another issue for that?

**Comment by tboegner** [comment]
In fact this error situation is already handled by the fix. I will update the pull request and resolve the conflicts.
