### ISSUE TITLE
Make private proxy url configurable

### ISSUE THREAD

**Issue by hey-johnnypark** [iris-connect/iris-client#162]
TARGET:

https://github.com/iris-connect/iris-client/blob/31c6140ef43da38b685352137f0fa3ccea06588b/infrastructure/deployment/conf/proxy/roles/private-proxy-eps/001_default.yml#L53

Endpoint to private proxy should be configurable through ENV variable.

**Comment by jekutzsche** [comment]
@hey-johnnypark 
The configuration is `endpoint: "http://$PRIVATE_PROXY_HOSTNAME:8877/jsonrpc"` now. Is the ticket done with that?

**Comment by hey-johnnypark** [comment]
Yes it is @jekutzsche
