### ISSUE TITLE
IRIS-Client | Installationsanleitung Standalone

### ISSUE THREAD

**Issue by Scotchomani** [iris-connect/iris-client#174]
Hallo IRIS-Team,

aufgrund interner Sicherheitsbedenken können wir die Docker Installation nicht benutzen.
Unser FD-Bereich hat sich hier für die Standalone Installation entschieden. 

Aktuell fehlt hierbei noch die vollständige Installationsanleitung
Könnte diese geupdatet werden ? 

Vielen Dank !

**Comment by hey-johnnypark** [comment]
Hi @Scotchomani , wir sind just in diesem Moment dran. Hier wird es zeitnah ein Update geben. Ihr seid nicht die einzigen mit dieser Challenge.
