### ISSUE TITLE
Rename environments

### ISSUE THREAD

**Issue by hey-johnnypark** [iris-connect/iris-client#180]
CURRENT

We have the situation where in the documentation we use the terms **staging** and **live** but the environments are called **test** and **prod**. 

TARGET

We should replace the terms **staging** and **live** from the documentation and use the terms **test** and **prod**.

**Comment by jekutzsche** [comment]
I cannot find anything where `test` and `prod` are used significantly. Overall it seems to me largely consistent with `staging` and `live` and since the ticket is already very old, I'll close it now.
