### ISSUE TITLE
Feature flag for index cases

### ISSUE THREAD

**Issue by hey-johnnypark** [iris-connect/iris-client#192]
CURRENT 

With merge of https://github.com/iris-connect/iris-client/pull/169 Index Cases feature is not visible. We need to implement a feature flag that explicitely activates the link in the navigation. 

Default should be deactivated.

**Comment by mad-nuts** [comment]
Feature is implemented: #194 

To enable Index Tracking features:
`[[URL]]?indexTracking=enabled`

To disable Index Tracking features:
`[[URL]]?indexTracking=disabled`

Please note:
- The default setting is "disabled".
- Enabling / disabling the feature triggers a reload of the page and removes the queryString automatically.
- The feature can be triggert on every page (even on index tracking pages).
- The enabled /disabled state is stored in localStorage.

As this is a temporary fix I've marked all code sections with comments like `@todo - indexTracking ...`

**Comment by mad-nuts** [comment]
@hey-johnnypark Feature is implemented and merged to develop. This ticket can be closed anytime from development perspective

**Comment by hey-johnnypark** [comment]
Thanks @mad-nuts
