### ISSUE TITLE
Event Tracing Form: Ordentlicher Datetime-Picker

### ISSUE THREAD

**Issue by t0bska** [iris-connect/iris-client#2]
Es sollten beim Erstellen einer Ereignis-NV Anfangs- und End-Zeit jeweils mit Datum ausgewählt werden können.

Uhrzeit und Datum können in einem Input-Feld ausgewählt werden (`21.03.2021 12:55`) oder getrennt (ein Input Datum, ein Input Uhrzeit), wobei in beiden Fällen ein desktop-tauglicher Picker aufgehen sollte, aber auch eine Eingabe per Tastatur möglich sein sollte.

**Comment by topialla** [comment]
@t0bska ist erledigt, oder?

**Comment by stefanmichalk** [comment]
Kann erstmal so bleiben meiner Meinung nach.

Bug besteht allerdings beim Benutzen des Pickers. Hier rein oder neues Ticket?
Wobei das vernachlässigbar ist für Release.

**Comment by jekutzsche** [comment]
dürfte erledigt sein
