### ISSUE TITLE
opening details for a list of contacts should also come from the blue/red indicator

### ISSUE THREAD

**Issue by topialla** [iris-connect/iris-client#22]
Initial urge to see the delivered data was to click on the red button

![image](https://user-images.githubusercontent.com/2855408/113350922-6feb2600-933a-11eb-9613-c7fff0d6d723.png)

Perhaps just copy the "Details" functionality?

**Comment by stefanmichalk** [comment]
I would generally revise the color scheme.
The red is more of a warning than a "here we go".

Should be discussed with UX.

**Comment by jekutzsche** [comment]
We will not be making any changes here for the foreseeable future and are therefore closing this ticket.
