### ISSUE TITLE
The user must be able to change the password

### ISSUE THREAD

**Issue by Marko-ilmkreis** [iris-connect/iris-client#249]
Currently it is only possible that the admin sets the password. The user ist not able to change the password or to get a link to reset it if lost.

Please make the change of the passwords for users available.

**Comment by bkastl** [comment]
Hello @Marko-ilmkreis,

thanks for the pointer. We will update the user profile soon so that users will be able to change their passwords.

**Comment by jekutzsche** [comment]
Implemented with version 1.0.0-rc.13.
