### ISSUE TITLE
It is possible that the current user deletes itself

### ISSUE THREAD

**Issue by Marko-ilmkreis** [iris-connect/iris-client#250]
In the current configuration it is possible that the currently logged in user deletes itself without any warning beside the normale delete warning.

It should not be possible that the user, which is logged in, can deleted by him/herself. Otherwise there is a risk to lock-out of Iris.

**Comment by mad-nuts** [comment]
I'm taking care of the frontend part

**Comment by mad-nuts** [comment]
@jekutzsche Frontend part is done. I've created a pull request with the changes. Could you review it?

**Comment by jekutzsche** [comment]
Implemented with version 1.0.0-rc.13.
