### ISSUE TITLE
App documentation not up to date

### ISSUE THREAD

**Issue by hey-johnnypark** [iris-connect/iris-client#308]
CURRENT

For JRPC method submitGuestList the fields for address are described as non required. 

TARGET

With the IRIS Client Major version, those fields will be required and must not be blank. We need to update the documentation and inform the app providers.

**Comment by jekutzsche** [comment]
Fixes with https://github.com/iris-connect/iris-documentation/commit/f7c18469545bb7c9887bec6157ed45b148f8a7ad
