### ISSUE TITLE
Improve certification process

### ISSUE THREAD

**Issue by hey-johnnypark** [iris-connect/iris-client#349]
At the end of the certificate journey we should describe how to check which certificate is which.  

We describe 3 certificates. The downloaded file from Budru is something like mycert123123123.cer. 

We could provide a command (openssel) to check and describe what to look out for.

**Comment by mvonpapen** [comment]
Hey @hey-johnnypark ,
Danke für die Erstellung des issues.

Mit `openssl x509 -in myCert_2015089.cer -noout -subject` kann man sich die Details recht kompakt anzeigen. Da ist dann der CN gut zu erkennen. Würde vorschlagen, dass man am Ende folgenden Text hinzufügt:

> Die Bundesdruckerei übermittelt die Zertifikate mit einer durchlaufenden Nummerierung versehen, bspw. `myCert_1016059.cer`. Um nun zu überprüfen, welches Zertifikat das TLS Zertifikat #1 und welches das mTLS/EPS Zertifikat #3 ist, kann folgender Befehl verwendet werden:
> ```
> openssl x509 -in myCert_1016059.cer -noout -subject
> ```
> Als Ergebnis erhält man eine kompakte Liste von Einträgen, von denen zur Identifikation der Zertifikate der Common Name (CN) interessant ist. Das mTLS/EPS Zertifikat #3 sollte hier einen Eintrag in der Form `CN = eps.[DOMAIN_NAME]` enthalten.

**Comment by hey-johnnypark** [comment]
@mvonpapen PR created. Thanks 🤝
