### ISSUE TITLE
Request/Reset password view

### ISSUE THREAD

**Issue by feendrache** [iris-connect/iris-client#43]
there should be a request/reset password view for users, linked at the login view

how should it be managed? 
- reset password and user needs to set a new one?
- send the password given?

**Comment by jekutzsche** [comment]
In the usage scenarios of the IRIS client (specialist application within health departments), resetting the password is always possible via the admin. Therefore, this function is not necessary and we currently forgo the additional effort for implementation and the risk of misuse. There is also a way for the admin to act if they forget their password. 

Also, we currently do not have the email address to do anything here.
