### ISSUE TITLE
Use a random value for `SECURITY_JWT_JWT_SHARED_SECRET`

### ISSUE THREAD

**Issue by jekutzsche** [iris-connect/iris-client#553]
Setting `SECURITY_JWT_JWT_SHARED_SECRET` is a technical necessity that the HD admin should ideally not have anything to do with. Thus it is not ideal to do this in the `.env`.

It would be better to let Spring use a random value for the `SECURITY_JWT_SHARED_SECRET` property.

The only difference to the previous implementation is that the "old" JWTs don`t work after a restart. I think this is ok.

**Comment by jekutzsche** [comment]
@lucky-lusa what do you think?

**Comment by lucky-lusa** [comment]
Since the validity period of our tokens is very limited anyway, we are fine with having the token secrets randomly generated.
