### ISSUE TITLE
TokenExpiredException displayed to late

### ISSUE THREAD

**Issue by kowar** [iris-connect/iris-client#63]
User was not logged out before shutdown of Docker container. After container (re)-start you get browser login dialog and after success no login dialog from application was shown, you receive dashbord directly. In the footer an error-banner with no error-message is displayed. On click on any button you are routed to application login. 

Exception in logfile:

`com.auth0.jwt.exceptions.TokenExpiredException: The Token has expired on Tue May 04 13:58:28 UTC 2021.
←[35miris-client_1    |←[0m     at com.auth0.jwt.JWTVerifier.assertDateIsFuture(JWTVerifier.java:379) ~[java-jwt-3.10.3.jar:3.10.3]
←[35miris-client_1    |←[0m     at com.auth0.jwt.JWTVerifier.assertValidDateClaim(JWTVerifier.java:370) ~[java-jwt-3.10.3.jar:3.10.3]
←[35miris-client_1    |←[0m     at com.auth0.jwt.JWTVerifier.verifyClaims(JWTVerifier.java:295) ~[java-jwt-3.10.3.jar:3.10.3]
←[35miris-client_1    |←[0m     at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:278) ~[java-jwt-3.10.3.jar:3.10.3]
←[35miris-client_1    |←[0m     at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:261) ~[java-jwt-3.10.3.jar:3.10.3]
←[35miris-client_1    |←[0m     at de.healthIMIS.iris.client.auth.db.jwt.JWTService.verify(JWTService.java:31) ~[classes/:0.0.1-SNAPSHOT]
←[35miris-client_1    |←[0m     at de.healthIMIS.iris.client.auth.db.JWTAuthorizationFilter.authenticate(JWTAuthorizationFilter.java:51) ~[classes/:0.0.1-SNAPSHOT]
←[35miris-client_1    |←[0m     at de.healthIMIS.iris.client.auth.db.JWTAuthorizationFilter.doFilterInternal(JWTAuthorizationFilter.java:44) ~[classes/:0.0.1-SNAPSHOT]
←[35miris-client_1    |←[0m     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.3.jar:5.3.3]`

**Comment by jekutzsche** [comment]
Is outdated
