### ISSUE TITLE
clean up technical debts after accelerated merge to develop branch

### ISSUE THREAD

**Issue by bianucci** [iris-connect/iris-client#86]
TODOs:

1. create reusable constant for `/data-submission-rpc`
2. move rpc config from main class to new class in config package
3. error propagation to iris-client-fe in case data requests failed
4. error propagation to data-provider in case data submission failed
5. In `submitGuestList` assert that client name equals provider id
6. Search in code for `TODO check: why do we need to do this?` and investigate this cargo code.

**Comment by tboegner** [comment]
Topic 3 is now handled in separate issue:
https://github.com/iris-connect/iris-client/issues/128

**Comment by jekutzsche** [comment]
In the meantime, everything has been implemented.
